trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'Install npm packages'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Execute linters'
  inputs:
    command: 'custom'
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'Execute tests'
  inputs:
    command: 'custom'
    customCommand: 'run test'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
